version: '3.8'

services:
  backend:
    build:
      context: ./backend
    container_name: coupon_api
    volumes:
      - ./backend/db.sqlite3:/app/db.sqlite3
    ports:
      - "8000:8000"
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
    container_name: coupon_dashboard
    ports:
      - "8080:80"
    depends_on:
      - backend
    restart: unless-stopped