# Generated by Django 5.2.5 on 2025-08-11 14:57

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Coupon",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("country_code", models.CharField(default="us", max_length=10)),
                ("coupon_id", models.IntegerField()),
                (
                    "coupon_webshop_name",
                    models.CharField(db_index=True, max_length=255),
                ),
                ("description", models.TextField()),
                ("first_seen", models.DateField(blank=True, null=True)),
                ("last_seen", models.DateField(blank=True, null=True)),
                (
                    "promotion_type",
                    models.CharField(
                        choices=[
                            ("percent-off", "Percent Off"),
                            ("buy-one-get-one", "Buy One Get One"),
                            ("dollar-off", "Dollar Off"),
                            ("free-gift", "Free Gift"),
                            ("free-shipping", "Free Shipping"),
                        ],
                        db_index=True,
                        default=None,
                        max_length=50,
                        null=True,
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("value", models.IntegerField(null=True)),
                ("webshop_id", models.CharField(db_index=True, max_length=50)),
            ],
        ),
    ]
